server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/googleLogin?serverTimezone=Asia/Seoul
    username: google
    password: google1234

  jpa:
    hibernate:
      ddl-auto: create # 실행후 update로 변경
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Your Google Client ID
            client-secret: Your Google Client secret key
            scope:
              - email
              - profile